### ISSUE TITLE
Batch Edit not working

### ISSUE THREAD

**Issue by jamesvanmil** [uclibs/scholar_uc#1805]
Select one or more works on the dashboard and click 'Edit Selected'

`app/views/records/edit_fields/_creator.html.erb:2` throws an error:

`undefined local variable or method 'curation_concern'`

This was introduced with https://github.com/uclibs/scholar_uc/commit/73665af958e50821357e776f53a00d811904c21d
